name: LifeSteal
version: '${version}'
main: com.github.sokakmelodileri.lifesteal.LifeSteal
api-version: '1.20'
author: 'StreetMelodeez'
commands:
  gethealth:
    description: "gethealth"
    aliases: [ gethealth, gethp ]
    usage: "/gethealth <player>"
    permission: lifesteal.gethealth
    permission-message: "§cBu komutu kullanmak için yetkiniz yok!"
  sethealth:
    description: "sethealth"
    aliases: [ sethealth, sethp ]
    usage: "/sethealth <player> <amount>"
    permission: lifesteal.sethealth
    permission-message: "§cBu komutu kullanmak için yetkiniz yok!"
  withdraw:
    description: "withdraw"
    usage: "/withdraw <amount>"
    permission: lifesteal.withdraw
    permission-message: "§cBu komutu kullanmak için yetkiniz yok!"
  lifesteal:
    description: "lifesteal"
    aliases: [ lifesteal, ls ]
    usage: "/lifesteal <args>"
    permission: lifesteal.lifestealmain
    permission-message: "§cBu komutu kullanmak için yetkiniz yok!"
  getstick:
    description: "gives a revive stick"
    usage: "/getstick <amount>"
    permission: "lifesteal.admin"
    permission-message: "§cBu komutu kullanmak için yetkiniz yok!"